services:
  genesis:
    image: genesis-genesis:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genesis
    restart: always
    networks:
      - root_default
    env_file:
      - .env.local
    volumes:
      - genesis_data:/app/data
      - genesis_media:/app/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.genesis.rule=Host(`${GENESIS_SUBDOMAIN:-genesis.paulinhosiqueira.com.br}`)"
      - "traefik.http.routers.genesis.entrypoints=websecure"
      - "traefik.http.routers.genesis.tls.certresolver=mytlschallenge"
      - "traefik.http.services.genesis.loadbalancer.server.port=3000"

volumes:
  genesis_data:
    driver: local
  genesis_media:
    driver: local

networks:
  root_default:
    external: true
